package scanner

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

var testLoxCode = `
print "Hello, world!";

var imAVariable = "here is my value";
var iAmNil;
iAmNil == nil // true

var breakfast = "bagels";
print breakfast; // "bagels".
breakfast = "beignets";
print breakfast; // "beignets".

var addition = 1 + 1; // 2
var subtraction = 1 - 1; // 0
var multiplication = 1.0 * 1.0; // 1.0
var division = 2.0 / 1.0; // 2.0

var negation = -1; // -1

100 < 101; // true
101 <= 100; // false
100 > 101; // false
101 >= 101; // true

1 == 2;         // false
"cat" != "dog"; // true

123 != "123"; // true

!true;  // false
!false; // true

true and false; // false
true and true;  // true

false or false; // false
true or false;  // true

var average = (1 + 1) / 2; // 1

if (true) {
    print "yes";
  } else {
    print "no";
}

var a = 1;
while (a < 10) {
  print a;
  a = a + 1;
}

for (var a = 1; a < 10; a = a + 1) {
  print a;
}

fun printSum(a, b) {
  print a + b;
}

fun returnSum(a, b) {
  return a + b;
}

fun addPair(a, b) {
  return a + b;
}

fun identity(a) {
  return a;
}

print identity(addPair)(1, 2); // Prints "3".

fun outerFunction() {
  fun localFunction() {
    print "I'm local!";
  }

  localFunction();
}

class Breakfast {
  cook() {
    print "Eggs a-fryin'!";
  }

  serve(who) {
    print "Enjoy your breakfast, " + who + ".";
  }
}

// Store it in variables.
var someVariable = Breakfast;

// Pass it to functions.
someFunction(Breakfast);

var breakfast = Breakfast();
print breakfast; // "Breakfast instance".

class Breakfast {
  init(meat, bread) {
    this.meat = meat;
    this.bread = bread;
  }

  serve(who) {
    print "Enjoy your " + this.meat + " and " +
        this.bread + ", " + who + ".";
  }

  // ...
}

class Brunch < Breakfast {
  init(meat, bread, drink) {
    super.init(meat, bread);
    this.drink = drink;
  }

  drink() {
    print "How about a Bloody Mary?";
  }
}
`

func TestScanner_Success(t *testing.T) {
	scnr := NewScanner(testLoxCode)

	isAtEnd := scnr.IsAtEnd()
	assert.False(t, isAtEnd)

	tokens, errs := scnr.ScanTokens()

	isAtEnd = scnr.IsAtEnd()
	assert.True(t, isAtEnd)

	assert.Nil(t, errs)

	expectedTokens := []*token{
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      2,
			position:  1,
		},
		{
			tokenType: String,
			lexeme:    `"Hello, world!"`,
			literal:   "Hello, world!",
			line:      2,
			position:  7,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      2,
			position:  22,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      4,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `imAVariable`,
			literal:   nil,
			line:      4,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      4,
			position:  17,
		},
		{
			tokenType: String,
			lexeme:    `"here is my value"`,
			literal:   "here is my value",
			line:      4,
			position:  19,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      4,
			position:  37,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      5,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `iAmNil`,
			literal:   nil,
			line:      5,
			position:  5,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      5,
			position:  11,
		},
		{
			tokenType: Identifier,
			lexeme:    `iAmNil`,
			literal:   nil,
			line:      6,
			position:  1,
		},
		{
			tokenType: EqualEqual,
			lexeme:    `==`,
			literal:   nil,
			line:      6,
			position:  8,
		},
		{
			tokenType: Nil,
			lexeme:    `nil`,
			literal:   nil,
			line:      6,
			position:  11,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      8,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `breakfast`,
			literal:   nil,
			line:      8,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      8,
			position:  15,
		},
		{
			tokenType: String,
			lexeme:    `"bagels"`,
			literal:   "bagels",
			line:      8,
			position:  17,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      8,
			position:  25,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      9,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `breakfast`,
			literal:   nil,
			line:      9,
			position:  7,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      9,
			position:  16,
		},
		{
			tokenType: Identifier,
			lexeme:    `breakfast`,
			literal:   nil,
			line:      10,
			position:  1,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      10,
			position:  11,
		},
		{
			tokenType: String,
			lexeme:    `"beignets"`,
			literal:   "beignets",
			line:      10,
			position:  13,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      10,
			position:  23,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      11,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `breakfast`,
			literal:   nil,
			line:      11,
			position:  7,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      11,
			position:  16,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      13,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `addition`,
			literal:   nil,
			line:      13,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      13,
			position:  14,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      13,
			position:  16,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      13,
			position:  18,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      13,
			position:  20,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      13,
			position:  21,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      14,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `subtraction`,
			literal:   nil,
			line:      14,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      14,
			position:  17,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      14,
			position:  19,
		},
		{
			tokenType: Minus,
			lexeme:    `-`,
			literal:   nil,
			line:      14,
			position:  21,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      14,
			position:  23,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      14,
			position:  24,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      15,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `multiplication`,
			literal:   nil,
			line:      15,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      15,
			position:  20,
		},
		{
			tokenType: Number,
			lexeme:    `1.0`,
			literal:   1.0,
			line:      15,
			position:  22,
		},
		{
			tokenType: Star,
			lexeme:    `*`,
			literal:   nil,
			line:      15,
			position:  26,
		},
		{
			tokenType: Number,
			lexeme:    `1.0`,
			literal:   1.0,
			line:      15,
			position:  28,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      15,
			position:  31,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      16,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `division`,
			literal:   nil,
			line:      16,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      16,
			position:  14,
		},
		{
			tokenType: Number,
			lexeme:    `2.0`,
			literal:   2.0,
			line:      16,
			position:  16,
		},
		{
			tokenType: Slash,
			lexeme:    `/`,
			literal:   nil,
			line:      16,
			position:  20,
		},
		{
			tokenType: Number,
			lexeme:    `1.0`,
			literal:   1.0,
			line:      16,
			position:  22,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      16,
			position:  25,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      18,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `negation`,
			literal:   nil,
			line:      18,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      18,
			position:  14,
		},
		{
			tokenType: Minus,
			lexeme:    `-`,
			literal:   nil,
			line:      18,
			position:  16,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      18,
			position:  17,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      18,
			position:  18,
		},
		{
			tokenType: Number,
			lexeme:    `100`,
			literal:   100.0,
			line:      20,
			position:  1,
		},
		{
			tokenType: Less,
			lexeme:    `<`,
			literal:   nil,
			line:      20,
			position:  5,
		},
		{
			tokenType: Number,
			lexeme:    `101`,
			literal:   101.0,
			line:      20,
			position:  7,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      20,
			position:  10,
		},
		{
			tokenType: Number,
			lexeme:    `101`,
			literal:   101.0,
			line:      21,
			position:  1,
		},
		{
			tokenType: LessEqual,
			lexeme:    `<=`,
			literal:   nil,
			line:      21,
			position:  5,
		},
		{
			tokenType: Number,
			lexeme:    `100`,
			literal:   100.0,
			line:      21,
			position:  8,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      21,
			position:  11,
		},
		{
			tokenType: Number,
			lexeme:    `100`,
			literal:   100.0,
			line:      22,
			position:  1,
		},
		{
			tokenType: Greater,
			lexeme:    `>`,
			literal:   nil,
			line:      22,
			position:  5,
		},
		{
			tokenType: Number,
			lexeme:    `101`,
			literal:   101.0,
			line:      22,
			position:  7,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      22,
			position:  10,
		},
		{
			tokenType: Number,
			lexeme:    `101`,
			literal:   101.0,
			line:      23,
			position:  1,
		},
		{
			tokenType: GreaterEqual,
			lexeme:    `>=`,
			literal:   nil,
			line:      23,
			position:  5,
		},
		{
			tokenType: Number,
			lexeme:    `101`,
			literal:   101.0,
			line:      23,
			position:  8,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      23,
			position:  11,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      25,
			position:  1,
		},
		{
			tokenType: EqualEqual,
			lexeme:    `==`,
			literal:   nil,
			line:      25,
			position:  3,
		},
		{
			tokenType: Number,
			lexeme:    `2`,
			literal:   2.0,
			line:      25,
			position:  6,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      25,
			position:  7,
		},
		{
			tokenType: String,
			lexeme:    `"cat"`,
			literal:   "cat",
			line:      26,
			position:  1,
		},
		{
			tokenType: BangEqual,
			lexeme:    `!=`,
			literal:   nil,
			line:      26,
			position:  7,
		},
		{
			tokenType: String,
			lexeme:    `"dog"`,
			literal:   "dog",
			line:      26,
			position:  10,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      26,
			position:  15,
		},
		{
			tokenType: Number,
			lexeme:    `123`,
			literal:   123.0,
			line:      28,
			position:  1,
		},
		{
			tokenType: BangEqual,
			lexeme:    `!=`,
			literal:   nil,
			line:      28,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"123"`,
			literal:   "123",
			line:      28,
			position:  8,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      28,
			position:  13,
		},
		{
			tokenType: Bang,
			lexeme:    `!`,
			literal:   nil,
			line:      30,
			position:  1,
		},
		{
			tokenType: True,
			lexeme:    `true`,
			literal:   nil,
			line:      30,
			position:  2,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      30,
			position:  6,
		},
		{
			tokenType: Bang,
			lexeme:    `!`,
			literal:   nil,
			line:      31,
			position:  1,
		},
		{
			tokenType: False,
			lexeme:    `false`,
			literal:   nil,
			line:      31,
			position:  2,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      31,
			position:  7,
		},
		{
			tokenType: True,
			lexeme:    `true`,
			literal:   nil,
			line:      33,
			position:  1,
		},
		{
			tokenType: And,
			lexeme:    `and`,
			literal:   nil,
			line:      33,
			position:  6,
		},
		{
			tokenType: False,
			lexeme:    `false`,
			literal:   nil,
			line:      33,
			position:  10,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      33,
			position:  15,
		},
		{
			tokenType: True,
			lexeme:    `true`,
			literal:   nil,
			line:      34,
			position:  1,
		},
		{
			tokenType: And,
			lexeme:    `and`,
			literal:   nil,
			line:      34,
			position:  6,
		},
		{
			tokenType: True,
			lexeme:    `true`,
			literal:   nil,
			line:      34,
			position:  10,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      34,
			position:  14,
		},
		{
			tokenType: False,
			lexeme:    `false`,
			literal:   nil,
			line:      36,
			position:  1,
		},
		{
			tokenType: Or,
			lexeme:    `or`,
			literal:   nil,
			line:      36,
			position:  7,
		},
		{
			tokenType: False,
			lexeme:    `false`,
			literal:   nil,
			line:      36,
			position:  10,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      36,
			position:  15,
		},
		{
			tokenType: True,
			lexeme:    `true`,
			literal:   nil,
			line:      37,
			position:  1,
		},
		{
			tokenType: Or,
			lexeme:    `or`,
			literal:   nil,
			line:      37,
			position:  6,
		},
		{
			tokenType: False,
			lexeme:    `false`,
			literal:   nil,
			line:      37,
			position:  9,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      37,
			position:  14,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      39,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `average`,
			literal:   nil,
			line:      39,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      39,
			position:  13,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      39,
			position:  15,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      39,
			position:  16,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      39,
			position:  18,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      39,
			position:  20,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      39,
			position:  21,
		},
		{
			tokenType: Slash,
			lexeme:    `/`,
			literal:   nil,
			line:      39,
			position:  23,
		},
		{
			tokenType: Number,
			lexeme:    `2`,
			literal:   2.0,
			line:      39,
			position:  25,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      39,
			position:  26,
		},
		{
			tokenType: If,
			lexeme:    `if`,
			literal:   nil,
			line:      41,
			position:  1,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      41,
			position:  4,
		},
		{
			tokenType: True,
			lexeme:    `true`,
			literal:   nil,
			line:      41,
			position:  5,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      41,
			position:  9,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      41,
			position:  11,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      42,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"yes"`,
			literal:   "yes",
			line:      42,
			position:  11,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      42,
			position:  16,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      43,
			position:  3,
		},
		{
			tokenType: Else,
			lexeme:    `else`,
			literal:   nil,
			line:      43,
			position:  5,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      43,
			position:  10,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      44,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"no"`,
			literal:   "no",
			line:      44,
			position:  11,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      44,
			position:  15,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      45,
			position:  1,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      47,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      47,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      47,
			position:  7,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      47,
			position:  9,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      47,
			position:  10,
		},
		{
			tokenType: While,
			lexeme:    `while`,
			literal:   nil,
			line:      48,
			position:  1,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      48,
			position:  7,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      48,
			position:  8,
		},
		{
			tokenType: Less,
			lexeme:    `<`,
			literal:   nil,
			line:      48,
			position:  10,
		},
		{
			tokenType: Number,
			lexeme:    `10`,
			literal:   10.0,
			line:      48,
			position:  12,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      48,
			position:  14,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      48,
			position:  16,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      49,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      49,
			position:  9,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      49,
			position:  10,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      50,
			position:  3,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      50,
			position:  5,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      50,
			position:  7,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      50,
			position:  9,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      50,
			position:  11,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      50,
			position:  12,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      51,
			position:  1,
		},
		{
			tokenType: For,
			lexeme:    `for`,
			literal:   nil,
			line:      53,
			position:  1,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      53,
			position:  5,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      53,
			position:  6,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      53,
			position:  10,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      53,
			position:  12,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      53,
			position:  14,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      53,
			position:  15,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      53,
			position:  17,
		},
		{
			tokenType: Less,
			lexeme:    `<`,
			literal:   nil,
			line:      53,
			position:  19,
		},
		{
			tokenType: Number,
			lexeme:    `10`,
			literal:   10.0,
			line:      53,
			position:  21,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      53,
			position:  23,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      53,
			position:  25,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      53,
			position:  27,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      53,
			position:  29,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      53,
			position:  31,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      53,
			position:  33,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      53,
			position:  34,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      53,
			position:  36,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      54,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      54,
			position:  9,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      54,
			position:  10,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      55,
			position:  1,
		},
		{
			tokenType: Fun,
			lexeme:    `fun`,
			literal:   nil,
			line:      57,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `printSum`,
			literal:   nil,
			line:      57,
			position:  5,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      57,
			position:  13,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      57,
			position:  14,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      57,
			position:  15,
		},
		{
			tokenType: Identifier,
			lexeme:    `b`,
			literal:   nil,
			line:      57,
			position:  17,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      57,
			position:  18,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      57,
			position:  20,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      58,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      58,
			position:  9,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      58,
			position:  11,
		},
		{
			tokenType: Identifier,
			lexeme:    `b`,
			literal:   nil,
			line:      58,
			position:  13,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      58,
			position:  14,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      59,
			position:  1,
		},
		{
			tokenType: Fun,
			lexeme:    `fun`,
			literal:   nil,
			line:      61,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `returnSum`,
			literal:   nil,
			line:      61,
			position:  5,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      61,
			position:  14,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      61,
			position:  15,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      61,
			position:  16,
		},
		{
			tokenType: Identifier,
			lexeme:    `b`,
			literal:   nil,
			line:      61,
			position:  18,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      61,
			position:  19,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      61,
			position:  21,
		},
		{
			tokenType: Return,
			lexeme:    `return`,
			literal:   nil,
			line:      62,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      62,
			position:  10,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      62,
			position:  12,
		},
		{
			tokenType: Identifier,
			lexeme:    `b`,
			literal:   nil,
			line:      62,
			position:  14,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      62,
			position:  15,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      63,
			position:  1,
		},
		{
			tokenType: Fun,
			lexeme:    `fun`,
			literal:   nil,
			line:      65,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `addPair`,
			literal:   nil,
			line:      65,
			position:  5,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      65,
			position:  12,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      65,
			position:  13,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      65,
			position:  14,
		},
		{
			tokenType: Identifier,
			lexeme:    `b`,
			literal:   nil,
			line:      65,
			position:  16,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      65,
			position:  17,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      65,
			position:  19,
		},
		{
			tokenType: Return,
			lexeme:    `return`,
			literal:   nil,
			line:      66,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      66,
			position:  10,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      66,
			position:  12,
		},
		{
			tokenType: Identifier,
			lexeme:    `b`,
			literal:   nil,
			line:      66,
			position:  14,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      66,
			position:  15,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      67,
			position:  1,
		},
		{
			tokenType: Fun,
			lexeme:    `fun`,
			literal:   nil,
			line:      69,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `identity`,
			literal:   nil,
			line:      69,
			position:  5,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      69,
			position:  13,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      69,
			position:  14,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      69,
			position:  15,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      69,
			position:  17,
		},
		{
			tokenType: Return,
			lexeme:    `return`,
			literal:   nil,
			line:      70,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `a`,
			literal:   nil,
			line:      70,
			position:  10,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      70,
			position:  11,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      71,
			position:  1,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      73,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `identity`,
			literal:   nil,
			line:      73,
			position:  7,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      73,
			position:  15,
		},
		{
			tokenType: Identifier,
			lexeme:    `addPair`,
			literal:   nil,
			line:      73,
			position:  16,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      73,
			position:  23,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      73,
			position:  24,
		},
		{
			tokenType: Number,
			lexeme:    `1`,
			literal:   1.0,
			line:      73,
			position:  25,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      73,
			position:  26,
		},
		{
			tokenType: Number,
			lexeme:    `2`,
			literal:   2.0,
			line:      73,
			position:  28,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      73,
			position:  29,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      73,
			position:  30,
		},
		{
			tokenType: Fun,
			lexeme:    `fun`,
			literal:   nil,
			line:      75,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `outerFunction`,
			literal:   nil,
			line:      75,
			position:  5,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      75,
			position:  18,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      75,
			position:  19,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      75,
			position:  21,
		},
		{
			tokenType: Fun,
			lexeme:    `fun`,
			literal:   nil,
			line:      76,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `localFunction`,
			literal:   nil,
			line:      76,
			position:  7,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      76,
			position:  20,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      76,
			position:  21,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      76,
			position:  23,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      77,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"I'm local!"`,
			literal:   "I'm local!",
			line:      77,
			position:  11,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      77,
			position:  23,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      78,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `localFunction`,
			literal:   nil,
			line:      80,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      80,
			position:  16,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      80,
			position:  17,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      80,
			position:  18,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      81,
			position:  1,
		},
		{
			tokenType: Class,
			lexeme:    `class`,
			literal:   nil,
			line:      83,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `Breakfast`,
			literal:   nil,
			line:      83,
			position:  7,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      83,
			position:  17,
		},
		{
			tokenType: Identifier,
			lexeme:    `cook`,
			literal:   nil,
			line:      84,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      84,
			position:  7,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      84,
			position:  8,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      84,
			position:  10,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      85,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"Eggs a-fryin'!"`,
			literal:   "Eggs a-fryin'!",
			line:      85,
			position:  11,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      85,
			position:  27,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      86,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `serve`,
			literal:   nil,
			line:      88,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      88,
			position:  8,
		},
		{
			tokenType: Identifier,
			lexeme:    `who`,
			literal:   nil,
			line:      88,
			position:  9,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      88,
			position:  12,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      88,
			position:  14,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      89,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"Enjoy your breakfast, "`,
			literal:   "Enjoy your breakfast, ",
			line:      89,
			position:  11,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      89,
			position:  36,
		},
		{
			tokenType: Identifier,
			lexeme:    `who`,
			literal:   nil,
			line:      89,
			position:  38,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      89,
			position:  42,
		},
		{
			tokenType: String,
			lexeme:    `"."`,
			literal:   ".",
			line:      89,
			position:  44,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      89,
			position:  47,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      90,
			position:  3,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      91,
			position:  1,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      94,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `someVariable`,
			literal:   nil,
			line:      94,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      94,
			position:  18,
		},
		{
			tokenType: Identifier,
			lexeme:    `Breakfast`,
			literal:   nil,
			line:      94,
			position:  20,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      94,
			position:  29,
		},
		{
			tokenType: Identifier,
			lexeme:    `someFunction`,
			literal:   nil,
			line:      97,
			position:  1,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      97,
			position:  13,
		},
		{
			tokenType: Identifier,
			lexeme:    `Breakfast`,
			literal:   nil,
			line:      97,
			position:  14,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      97,
			position:  23,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      97,
			position:  24,
		},
		{
			tokenType: Var,
			lexeme:    `var`,
			literal:   nil,
			line:      99,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `breakfast`,
			literal:   nil,
			line:      99,
			position:  5,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      99,
			position:  15,
		},
		{
			tokenType: Identifier,
			lexeme:    `Breakfast`,
			literal:   nil,
			line:      99,
			position:  17,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      99,
			position:  26,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      99,
			position:  27,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      99,
			position:  28,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      100,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `breakfast`,
			literal:   nil,
			line:      100,
			position:  7,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      100,
			position:  16,
		},
		{
			tokenType: Class,
			lexeme:    `class`,
			literal:   nil,
			line:      102,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `Breakfast`,
			literal:   nil,
			line:      102,
			position:  7,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      102,
			position:  17,
		},
		{
			tokenType: Identifier,
			lexeme:    `init`,
			literal:   nil,
			line:      103,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      103,
			position:  7,
		},
		{
			tokenType: Identifier,
			lexeme:    `meat`,
			literal:   nil,
			line:      103,
			position:  8,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      103,
			position:  12,
		},
		{
			tokenType: Identifier,
			lexeme:    `bread`,
			literal:   nil,
			line:      103,
			position:  14,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      103,
			position:  19,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      103,
			position:  21,
		},
		{
			tokenType: This,
			lexeme:    `this`,
			literal:   nil,
			line:      104,
			position:  5,
		},
		{
			tokenType: Dot,
			lexeme:    `.`,
			literal:   nil,
			line:      104,
			position:  9,
		},
		{
			tokenType: Identifier,
			lexeme:    `meat`,
			literal:   nil,
			line:      104,
			position:  10,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      104,
			position:  15,
		},
		{
			tokenType: Identifier,
			lexeme:    `meat`,
			literal:   nil,
			line:      104,
			position:  17,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      104,
			position:  21,
		},
		{
			tokenType: This,
			lexeme:    `this`,
			literal:   nil,
			line:      105,
			position:  5,
		},
		{
			tokenType: Dot,
			lexeme:    `.`,
			literal:   nil,
			line:      105,
			position:  9,
		},
		{
			tokenType: Identifier,
			lexeme:    `bread`,
			literal:   nil,
			line:      105,
			position:  10,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      105,
			position:  16,
		},
		{
			tokenType: Identifier,
			lexeme:    `bread`,
			literal:   nil,
			line:      105,
			position:  18,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      105,
			position:  23,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      106,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `serve`,
			literal:   nil,
			line:      108,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      108,
			position:  8,
		},
		{
			tokenType: Identifier,
			lexeme:    `who`,
			literal:   nil,
			line:      108,
			position:  9,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      108,
			position:  12,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      108,
			position:  14,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      109,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"Enjoy your "`,
			literal:   "Enjoy your ",
			line:      109,
			position:  11,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      109,
			position:  25,
		},
		{
			tokenType: This,
			lexeme:    `this`,
			literal:   nil,
			line:      109,
			position:  27,
		},
		{
			tokenType: Dot,
			lexeme:    `.`,
			literal:   nil,
			line:      109,
			position:  31,
		},
		{
			tokenType: Identifier,
			lexeme:    `meat`,
			literal:   nil,
			line:      109,
			position:  32,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      109,
			position:  37,
		},
		{
			tokenType: String,
			lexeme:    `" and "`,
			literal:   " and ",
			line:      109,
			position:  39,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      109,
			position:  47,
		},
		{
			tokenType: This,
			lexeme:    `this`,
			literal:   nil,
			line:      110,
			position:  9,
		},
		{
			tokenType: Dot,
			lexeme:    `.`,
			literal:   nil,
			line:      110,
			position:  13,
		},
		{
			tokenType: Identifier,
			lexeme:    `bread`,
			literal:   nil,
			line:      110,
			position:  14,
		},

		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      110,
			position:  20,
		},
		{
			tokenType: String,
			lexeme:    `", "`,
			literal:   ", ",
			line:      110,
			position:  22,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      110,
			position:  27,
		},
		{
			tokenType: Identifier,
			lexeme:    `who`,
			literal:   nil,
			line:      110,
			position:  29,
		},
		{
			tokenType: Plus,
			lexeme:    `+`,
			literal:   nil,
			line:      110,
			position:  33,
		},
		{
			tokenType: String,
			lexeme:    `"."`,
			literal:   ".",
			line:      110,
			position:  35,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      110,
			position:  38,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      111,
			position:  3,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      114,
			position:  1,
		},
		{
			tokenType: Class,
			lexeme:    `class`,
			literal:   nil,
			line:      116,
			position:  1,
		},
		{
			tokenType: Identifier,
			lexeme:    `Brunch`,
			literal:   nil,
			line:      116,
			position:  7,
		},
		{
			tokenType: Less,
			lexeme:    `<`,
			literal:   nil,
			line:      116,
			position:  14,
		},
		{
			tokenType: Identifier,
			lexeme:    `Breakfast`,
			literal:   nil,
			line:      116,
			position:  16,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      116,
			position:  26,
		},
		{
			tokenType: Identifier,
			lexeme:    `init`,
			literal:   nil,
			line:      117,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      117,
			position:  7,
		},
		{
			tokenType: Identifier,
			lexeme:    `meat`,
			literal:   nil,
			line:      117,
			position:  8,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      117,
			position:  12,
		},
		{
			tokenType: Identifier,
			lexeme:    `bread`,
			literal:   nil,
			line:      117,
			position:  14,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      117,
			position:  19,
		},
		{
			tokenType: Identifier,
			lexeme:    `drink`,
			literal:   nil,
			line:      117,
			position:  21,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      117,
			position:  26,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      117,
			position:  28,
		},
		{
			tokenType: Super,
			lexeme:    `super`,
			literal:   nil,
			line:      118,
			position:  5,
		},
		{
			tokenType: Dot,
			lexeme:    `.`,
			literal:   nil,
			line:      118,
			position:  10,
		},
		{
			tokenType: Identifier,
			lexeme:    `init`,
			literal:   nil,
			line:      118,
			position:  11,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      118,
			position:  15,
		},
		{
			tokenType: Identifier,
			lexeme:    `meat`,
			literal:   nil,
			line:      118,
			position:  16,
		},
		{
			tokenType: Comma,
			lexeme:    `,`,
			literal:   nil,
			line:      118,
			position:  20,
		},
		{
			tokenType: Identifier,
			lexeme:    `bread`,
			literal:   nil,
			line:      118,
			position:  22,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      118,
			position:  27,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      118,
			position:  28,
		},
		{
			tokenType: This,
			lexeme:    `this`,
			literal:   nil,
			line:      119,
			position:  5,
		},
		{
			tokenType: Dot,
			lexeme:    `.`,
			literal:   nil,
			line:      119,
			position:  9,
		},
		{
			tokenType: Identifier,
			lexeme:    `drink`,
			literal:   nil,
			line:      119,
			position:  10,
		},
		{
			tokenType: Equal,
			lexeme:    `=`,
			literal:   nil,
			line:      119,
			position:  16,
		},
		{
			tokenType: Identifier,
			lexeme:    `drink`,
			literal:   nil,
			line:      119,
			position:  18,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      119,
			position:  23,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      120,
			position:  3,
		},
		{
			tokenType: Identifier,
			lexeme:    `drink`,
			literal:   nil,
			line:      122,
			position:  3,
		},
		{
			tokenType: LeftParen,
			lexeme:    `(`,
			literal:   nil,
			line:      122,
			position:  8,
		},
		{
			tokenType: RightParen,
			lexeme:    `)`,
			literal:   nil,
			line:      122,
			position:  9,
		},
		{
			tokenType: LeftBrace,
			lexeme:    `{`,
			literal:   nil,
			line:      122,
			position:  11,
		},
		{
			tokenType: Print,
			lexeme:    `print`,
			literal:   nil,
			line:      123,
			position:  5,
		},
		{
			tokenType: String,
			lexeme:    `"How about a Bloody Mary?"`,
			literal:   "How about a Bloody Mary?",
			line:      123,
			position:  11,
		},
		{
			tokenType: Semicolon,
			lexeme:    `;`,
			literal:   nil,
			line:      123,
			position:  37,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      124,
			position:  3,
		},
		{
			tokenType: RightBrace,
			lexeme:    `}`,
			literal:   nil,
			line:      125,
			position:  1,
		},
		{
			tokenType: EOF,
			lexeme:    ``,
			literal:   nil,
			line:      125,
			position:  1,
		},
	}

	for i, tkn := range tokens {
		assert.Equal(t, expectedTokens[i], tkn)
	}
}
